// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://kyjuwizqndxvbuswmkiw.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imt5anV3aXpxbmR4dmJ1c3dta2l3Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzU2Mjk4NDIsImV4cCI6MjA1MTIwNTg0Mn0.5vVmSV2tkjzu8vkr-jntCh72DB7a7_BcZYZqiFErIO0";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);